<?php
/**
 * CSF Firewall - Translated from Perl to PHP
 * ConfigServer Firewall & Login Failure Daemon (LFD)
 * 
 * This is a PHP translation of the original Perl-based CSF firewall
 * LFD (Login Failure Daemon) remains in C for performance
 * 
 * @version 1.0
 * @author CSF Translation
 */

// Define CSF paths and constants
define('CSF_PATH', '/usr/local/csf');
define('CSF_BIN', CSF_PATH . '/bin');
define('CSF_LIB', CSF_PATH . '/lib');
define('CSF_CONF', '/etc/csf');
define('CSF_VAR', '/var/lib/csf');
define('CSF_LOG', '/var/log/csf');
define('CSF_TMP', '/tmp/csf');

// CSF Version
define('CSF_VERSION', '15.10');

// CSF Configuration
$csf_config = array();
$csf_rules = array();
$csf_whitelist = array();
$csf_blacklist = array();

/**
 * Initialize CSF environment
 * 
 * @return bool
 */
function csf_init() {
    global $csf_config;
    
    if (!is_dir(CSF_CONF)) {
        return false;
    }
    
    // Load main configuration
    $config_file = CSF_CONF . '/csf.conf';
    
    if (!file_exists($config_file)) {
        return false;
    }
    
    // Parse configuration file
    $lines = file($config_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    
    foreach ($lines as $line) {
        $line = trim($line);
        
        // Skip comments
        if (substr($line, 0, 1) === '#') {
            continue;
        }
        
        // Parse configuration
        if (strpos($line, ' = ') !== false) {
            list($key, $value) = explode(' = ', $line, 2);
            $key = trim($key);
            $value = trim($value, ' "\'');
            $csf_config[$key] = $value;
        }
    }
    
    // Ensure necessary directories exist
    $required_dirs = array(CSF_VAR, CSF_LOG, CSF_TMP);
    
    foreach ($required_dirs as $dir) {
        if (!is_dir($dir)) {
            @mkdir($dir, 0755, true);
        }
    }
    
    return true;
}

/**
 * Get configuration value
 * 
 * @param string $key Configuration key
 * @param mixed $default Default value if not found
 * @return mixed Configuration value
 */
function csf_get_config($key, $default = null) {
    global $csf_config;
    
    return isset($csf_config[$key]) ? $csf_config[$key] : $default;
}

/**
 * Set configuration value
 * 
 * @param string $key Configuration key
 * @param mixed $value Configuration value
 * @return bool
 */
function csf_set_config($key, $value) {
    global $csf_config;
    $csf_config[$key] = $value;
    return true;
}

/**
 * Save configuration to file
 * 
 * @return bool
 */
function csf_save_config() {
    global $csf_config;
    
    $config_file = CSF_CONF . '/csf.conf';
    
    if (!is_writable($config_file)) {
        return false;
    }
    
    $content = "# ConfigServer Firewall Configuration\n";
    $content .= "# Generated by CSF PHP v" . CSF_VERSION . "\n";
    $content .= "# Date: " . date('Y-m-d H:i:s') . "\n\n";
    
    foreach ($csf_config as $key => $value) {
        if (is_bool($value)) {
            $value = $value ? '1' : '0';
        }
        
        if (strpos($value, ' ') !== false) {
            $value = '"' . $value . '"';
        }
        
        $content .= $key . ' = ' . $value . "\n";
    }
    
    // Create backup
    if (file_exists($config_file)) {
        copy($config_file, $config_file . '.bak');
    }
    
    // Write new configuration
    if (file_put_contents($config_file, $content) === false) {
        return false;
    }
    
    // Restore permissions
    @chmod($config_file, 0600);
    
    return true;
}

/**
 * Log CSF actions
 * 
 * @param string $message Log message
 * @param string $level Log level (INFO, WARN, ERROR)
 * @param string $module Module name
 * @return bool
 */
function csf_log($message, $level = 'INFO', $module = 'CSF') {
    $log_file = CSF_LOG . '/csf.log';
    
    $log_line = date('Y-m-d H:i:s') . ' [' . $level . '] [' . $module . '] ' . $message . "\n";
    
    // Create log file if it doesn't exist
    if (!file_exists($log_file)) {
        @touch($log_file);
        @chmod($log_file, 0600);
    }
    
    if (!is_writable($log_file)) {
        return false;
    }
    
    return file_put_contents($log_file, $log_line, FILE_APPEND) !== false;
}

/**
 * Load whitelist/allow list
 * 
 * @return array Whitelist entries
 */
function csf_load_whitelist() {
    global $csf_whitelist;
    
    $whitelist_file = CSF_CONF . '/csf.allow';
    
    if (!file_exists($whitelist_file)) {
        return array();
    }
    
    $lines = file($whitelist_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    
    foreach ($lines as $line) {
        $line = trim($line);
        
        if (empty($line) || substr($line, 0, 1) === '#') {
            continue;
        }
        
        $parts = explode('|', $line);
        
        if (count($parts) < 2) {
            continue;
        }
        
        $entry = array(
            'ip' => trim($parts[0]),
            'comment' => isset($parts[1]) ? trim($parts[1]) : '',
            'date' => isset($parts[2]) ? trim($parts[2]) : '',
        );
        
        $csf_whitelist[] = $entry;
    }
    
    return $csf_whitelist;
}

/**
 * Load blacklist/deny list
 * 
 * @return array Blacklist entries
 */
function csf_load_blacklist() {
    global $csf_blacklist;
    
    $blacklist_file = CSF_CONF . '/csf.deny';
    
    if (!file_exists($blacklist_file)) {
        return array();
    }
    
    $lines = file($blacklist_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    
    foreach ($lines as $line) {
        $line = trim($line);
        
        if (empty($line) || substr($line, 0, 1) === '#') {
            continue;
        }
        
        $parts = explode('|', $line);
        
        if (count($parts) < 2) {
            continue;
        }
        
        $entry = array(
            'ip' => trim($parts[0]),
            'comment' => isset($parts[1]) ? trim($parts[1]) : '',
            'date' => isset($parts[2]) ? trim($parts[2]) : '',
        );
        
        $csf_blacklist[] = $entry;
    }
    
    return $csf_blacklist;
}

// Initialize CSF on include
csf_init();
csf_load_whitelist();
csf_load_blacklist();
